micronaut:
  application:
    name: PetClinicReviews
  server:
    port: 8083

kafka:
  bootstrap:
    servers: localhost:9094

endpoints:
  all:
    enabled: true
    sensitive: false

mongodb:
  uri: mongodb://admin:admin@localhost:27017/pet-clinic-reviews?authSource=admin&authMechanism=SCRAM-SHA-1
  databaseName: pet-clinic-reviews
  collectionName: vet-reviews
