micronaut:
  application:
    name: Pet-Clinic-Reviews
mongodb:
  uri: mongodb://admin:admin@localhost:27017/pet-clinic-reviews?authSource=admin&authMechanism=SCRAM-SHA-1
  databaseName: pet-clinic-reviews
  collectionName: vet-reviews